### ISSUE TITLE
Sugestão de nova interface

### ISSUE THREAD

**Issue by wcalderipe** [VamosJuntas/back-end#13]
# Sugestão de nova interface

A API hoje possuí características de uma arquitetura SOA. Tendo em vista a depreciação desse tipo de serviço nos últimos anos e a grande onda de APIs RESTful que bate nas prais do mercado todos os dias criei essa issue para discutirmos juntos uma possível mudança em como os dados vão ser expostos aos futuros clientes; sugerindo algo mais parecido com o REST. ;)
## Interface hoje

A interface de _places_ expota hoje para consumidores divide-se em dois _endpoints_:

**GET** /risks-around - Busca por _places_ em um raio X.

**POST** /reports - Cria um novo report dentro de um _place_.

No ponto em que estamos em que temos apenas duas operações é fácil deduzir o que cada endpoint faz, porem num futuro que tenha mais operações e mais rotas para _places_ vamos acabar tendo nomenclaturas compostas para cada tipo de ação e sem falar nos arquivos de rotas gigantes. O que no meu ponto de vista não é muito intuitivo ao usuário (desenvolvedor).
## O principal modelo

Atualmente o modelo de dados é baseado em um único documento chamado _places_ que contém os atributos _loc, address_ e _reports_ como um agregado.

```
{
    loc: {
      type: [Number],
      index: '2d'
    },
    address: String,
    reports: [
      {
        category: String,
        date: Date,
        createdAt: {
          type: Date,
          default: Date.now
        }
      }
    ]
}
```
## Sugestão de interface REST

Observado o nosso modelo de dados é fácil identificar que estamos trabalhando apenas com entidades agregadas nesse dado momento. No REST usamos nested resources para representar esse tipo de documento, logo teriamos algo similar ao exemplo abaixo. 

Vou usar o ID como identificador de um determinado lugar mas acredito que esse não é o melhor jeito de trabalhar com geolocation. Talvez usar a latitude a longitude, como o Google Maps, faça mais sentido.
### Places

**GET** /places - Retorna uma lista com todos os _places_.

**GET** /places/:id - Retorna um determinado _place_.

**POST** /places - Cria um novo _place_.

**PUT** /places/:id - Atualiza todos os atributos de um _place_.

**PATCH** /places/:id - Atualiza parcialmente um _place_.
### Reports (nested resource)

**GET** /places/:place_id/reports - Retorna uma lista de todos os _reports_ agregados em um determinado _place_.

**POST** /places/:place_id/reports - Cria um novo _report_ em um determinado _place_.

**PUT** /places/:place_id/reports/:id - Atualiza um determinado _report_.

Acredito que apesar de maior essa interface é mais intuitiva para os desenvolvedores atualmente. ;)
### Mas e o /risks-around?

O _endpoint risks-around_ poderia ser feito através de filtros nos _query parameters_

**GET** /places/:id/reports?radius=100 ou /places/:lat,:long/reports?radius=100
### Outra utilidade para os filtros

Se caso no futuro o aplicativo use um mapa podemos usar um endpoint para listar todos os _places_ dentro de um raio X.

**GET** /places/:lat,:long?radius=1000

---

Vamos discutir juntos e chegar numa conclusão foda com ideias de todos :)

UM ABRAÇO E CAMIGOL!

**Comment by josigama** [comment]
Olá William, 

Gostei muito da sua sugestão de uma nova interface, pois está bem conciso e com idéias concretas. 
Vamos nos reunir semana que vem para discutir! Conte comigo!

Obrigada pelas sugestões. 

Abraços,

**Comment by wcalderipe** [comment]
Valeu Josi.. A ideia é jogar o conceito inicial aqui e se for de fato uma melhoria para o projeto amadurecer a ideia! :)

**Comment by tayanefernandes** [comment]
Curti muito!!!

**Comment by roberto** [comment]
- Vamos tentar manter em apenas uma request ao criar um report. Tanto pelo custo de realizar múltiplas requests quanto pela facilidade de uso da própria API. Então algo como `POST /places/:long,:lat/reports` seria mais interessante que `POST /places + POST /places/:place_id/reports`;
- `PUT /places/:place_id/reports/:id`: não se espera que os reports sejam atualizados:
  - é muito simples criar um, difícil ter algo erro que necessito de edição após;
  - não identificarmos quem criou;
-  `POST /places` não precisamos criar places, um place sem report não é nada no nosso sistema.;
- `/places/:lat,:long/reports?radius=100` faz muito sentido, com muito significado.

Gostei muito da proposta! Podemos começar com os serviços essenciais.

**Comment by tayanefernandes** [comment]
@roberto Quais por exemplo?

**Comment by wcalderipe** [comment]
Concordo contigo @roberto, criar um um _place_ tem que ser em uma única requisição para facilita o uso dos consumidores.

Seguindo a sugestão do Roberto de começar com os serviços essenciais acho que vamos acabar com algo muito parecido com isso:

**GET** /places - Lista todos os places. **(Revisar o uso)**

**GET** /places/:lat,:long/reports - Lista todos os _reports_ de um determinado _place_.

**POST** /places/:lat,:long/reports - Cria um novo _report_. Caso o _place_ não exista, cria ele também.

**GET** /places/:lat,:long/reports/:id - Retorna um determinado _place_.
**NOTA:** Talvez esse _endpoint_ faça mais sentido fora do _namespace places_, algo como /reports/:id.

**DELETE** /places/:lat,:long/reports/:id - Deleta um determinado _report_.
**NOTA:** Mesmo caso aqui, talvez faça mais sentido fora de _places_.

**Comment by otaviocarvalho** [comment]
Boa, @wcalderipe!

Obrigado pelas sugestões e por trazer essa discussão! Realmente precisamos parar para definir os endpoints, vai facilitar bastante o desenvolvimento.

😃

**Comment by MayraPaola** [comment]
O que acham na sessão de terça focar nesse assunto?

Todos podem participar?!
Em 26 de jun de 2016 2:50 PM, "Otávio Carvalho" notifications@github.com
escreveu:

**Comment by wcalderipe** [comment]
Definições da sessão de terça (28/06/2016)

### Documento de _reports_

```
{
    geolocation: {
      type: [Number],
      index: '2d'
    },
    category: String,
    date: Date,
    createdAt: {
      type: Date,
      default: Date.now
    }
}
```

### Endpoints

**GET** /reports/:lat,:long?radius=100

**POST** /reports/:lat,:long

**GET** /reports/20,21?radius=100&group=10

**Comment by otaviocarvalho** [comment]
A ser desenvolvido no novo repositório: https://github.com/VamosJuntas/vamosjuntas-api
